### ISSUE TITLE
Request for new P01 codes for Epibenthos dataset

### ISSUE THREAD

**Issue by Daphnisd** [iobis/vocab#3]
I'm processing a dataset with following parameters:
- Species distribution max depth
- Species distribution min depth
- Total cover of all species (%)

**Species distribution max depth**
- Proposed label: Maximum depth in sample of a biological entity specified elsewhere 
- Proposed definition: Maximum depth at which a biological entity specified elsewhere was observed in a sample. The parameter is typically used in case of a transect with different sub-samples collected at different depths.  

**Species distribution min depth**
- Proposed label: Minimum depth in sample of a biological entity specified elsewhere 
- Proposed definition: Minimum depth at which a biological entity specified elsewhere was observed in a sample. The parameter is typically used in case of a transect with different sub-samples collected at different depths.  

**Total cover of all species (%)**
- Proposed label: Coverage (in assayed sample) of the bed by all biological entities of the bed
- Proposed definition: The proportion of a given area of the seabed covered by biological entities. This coverage may exceed 100%.
--> similar to: http://vocab.nerc.ac.uk/collection/P01/current/SDBIOL10/

**Comment by gwemon** [comment]
Daphnis, I tried to remodel your terms based on our new semantic model/ontology.
For the species coverage code, we already have a number of concepts related to "Proportion" defined in our S06 vocabulary. See:
![image](https://user-images.githubusercontent.com/32506510/37521070-4356db60-2917-11e8-8496-40c93e12e46b.png)
So I wonder if we could convert "Coverage" to "Proportion (coverage)" defined as "The relative contribution of an entity relative to the total surface area sampled or observed."?

The new P01 PrefLabel based on the combination 
Property name='Proportion (coverage)'
Entity of interest='biota'
Matrix-property relationship='per unit area the' or may be simply "on the"
Matrix='bed'
would thus become: "Proportion (coverage) of biota per unit area of the bed"
or "Proportion (coverage) of biota on the bed"
Would that fit your requirement?
Is it okay to drop (in assayed sample)? In this use case I cannot see what it brings to the concept.

**Comment by gwemon** [comment]
For the min and max depths the semantic parsing could translate to:
Measured property= Depth
Statistical element = maximum/minimum
Entity of interest = biological entity specified elsewhere
Matrix/substrate = bed
Matrix-property relationship = on the
Giving the P01 PrefLabel e.g.: "Depth maximum of biological entity specified elsewhere on the bed"
with definition: 
"The maximum depth on the bed of any kind of water body at which a biological entity specified elsewhere in the data schema was observed during a sampling event. The parameter is typically used for transect sampling when sub-samples are collected at different depths along the transect."
Again I'd suggest dropping "in sample" as not necessary here.

**Comment by gwemon** [comment]
Regarding Percent coverage, could you give an example why/when coverage may exceed 100%? Is this because we are talking about the sum of individual species surface area coverage divided by surface area surveyed?

**Comment by Daphnisd** [comment]
I'm fine with using "Proportion (coverage)", will you change this in this term too? http://vocab.nerc.ac.uk/collection/P01/current/SDBIOL10/

I added the "(in assayed sample)" in analogy with http://vocab.nerc.ac.uk/collection/P01/current/OCOUNT01/ and http://vocab.nerc.ac.uk/collection/P01/current/ODRYBM01/, but you are right that it makes less sense here. (Maybe the definition should mention its a the measurement of the quadrant and not a calculated value). "Proportion (coverage) of biota on the bed"  would work. 

I'll check regarding the "exceed 100%" comment.


"Depth maximum of biological entity specified elsewhere on the bed". Could the maximum be added in front of the depth? It sound strange otherwise. 
If I read solely the parameter name, I think it's a descriptor of a species rather than something based on a single sample. The definition covers that it's about a sampling event, so I guess it's ok, but it could become confusing if someone needs a code to describe maximum depth a taxon can occur on the bed?

**Comment by gwemon** [comment]
We could define the quadrat as the physical entity? This would give us: "Proportion (coverage) of quadrat area by biota"

Yes if you want me to then I could also propagate the change to SDBIOL10.

I have never been comfortable with the use of "in assayed sample" because most of the things we measure and define are in an assayed sample so I find it unsettling that we specify it for certain kinds of measurements and not others.

The semantic model is designed so that the statistical qualifier comes after the property name. It works for standard deviations and errors but it's true that for mean, maximum and minimum it does look weird to a human user. We are optimising the semantic model to enable machine readability so at present we cannot make exceptions. However once all our terms are mapped to the new model and all the components are available via the ontology then we might be able to revisit the way the preferred label is compiled and allow IF statements to optimise the label for human readability.

Yes, I understand what you mean about avoiding the confusion between a species descriptor and an observation. P01 is primarily a vocabulary for observations and measurements though and it should not really be used for generic species descriptors. Maybe this is something we will have to be careful about in the future. I'll think about how best to prevent any misuse of the term.

**Comment by Daphnisd** [comment]
"Proportion (coverage) of quadrat area by biota" seems fine to me. (you would not include on the bed as it's no longer needed?). Please do change SDBIOL10 accordingly.

I'm still to get feedback about the 100% comment, but I guess it's is because u could have a layers of coverage. 

"Depth maximum of biological entity specified elsewhere on the bed" is fine then.

Thnx!

**Comment by OBISCanada** [comment]
I will comment soon – am at our cottage till tomorrow. It is freezing here!

Sent from Mail for Windows 10

**Comment by gwemon** [comment]
The following 3 codes have been created in relation to this request:

http://vocab.nerc.ac.uk/collection/P01/current/DMAX7117/	Depth maximum of biological entity specified elsewhere on the bed by epibenthic sampling
The maximum seafloor depth at which a biological entity specified elsewhere in the data schema was observed in a sample. The parameter is typically used in case of transect with different sub-samples collected at different depths.

http://vocab.nerc.ac.uk/collection/P01/current/DMIN7117/	Depth minimum of biological entity specified elsewhere on the bed by epibenthic sampling
The minimum seafloor depth at which a biological entity specified elsewhere in the data schema was observed in a sample. The parameter is typically used in case of transect with different sub-samples collected at different depths.

http://vocab.nerc.ac.uk/collection/P01/current/PMA08441/	Proportion coverage of macro vegetation (excluding crust-forming algae) within a given area of the bed
The proportion of the surface area of the bed occupied by vegetation attached to the substrate. Includes macroalgae and seagrasses and excludes encrusting algae.

They will be available from the vocab server after the overnight publication run.

**Comment by gwemon** [comment]
Hi Daphnis. Were these codes okay for you? Let me know if there are still any remaining issues. Gwen.
