### ISSUE TITLE
Request for new L22: Hyperbenthic sledge

### ISSUE THREAD

**Issue by Thomas-Lanssens** [iobis/vocab#5]
“Hyperbenthic sledge”

“A hyperbenthic sledge is used for the sampling of hyperbenthos. The sledge is divided into two compartments one above the other, each accommodated with a hyperbenthos net. In this way, a distinction can be made between hyperbenthos close to the seafloor and benthos occurring a little higher. There is some space between the bottom and the nets, so the nets float in the water column and don’t catch any sediment.”

**Comment by Daphnisd** [comment]
@gwemon
Is this a concept that can be added to the L22 vocabulary?  Is the definition sufficient?

**Comment by gwemon** [comment]
Please could you post the request to us by creating an new issue on https://github.com/nvs-vocabs/L22/issues? It will be picked up by my colleague Lou Darroch who looks after L22 concept creations.  She will be able to advise. Many thanks, Gwen.
